name: build
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.0'

    - name: lint
      run: make setup lint

    - name: build
      run: make build
