name: release
on:
  release:
    types: [published]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: parse release version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: thisiserico/stub/stub
        registry: docker.pkg.github.com
        dockerfile: ./cmd/stub/Dockerfile
        username: ${{ github.actor }}
        password: ${{ github.token }}
        tags: "latest,${{ env.RELEASE_VERSION }}"

