name: release
on:
  release:
    types: [published]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: thisiserico/stub/stub
        registry: docker.pkg.github.com
        dockerfile: ./cmd/stub/Dockerfile
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        tags: "latest,${{ github.ref }}"

